//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppTienda
{
    using System;
    using System.Collections.Generic;
    
    public partial class Caja
    {
        public int CajaID { get; set; }
        public Nullable<int> UsuarioID { get; set; }
        public Nullable<System.DateTime> FechaApertura { get; set; }
        public Nullable<System.DateTime> FechaCierre { get; set; }
        public decimal SaldoInicial { get; set; }
        public Nullable<decimal> SaldoFinal { get; set; }
        public string Estado { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
