//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppTienda
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compras
    {
        public Compras()
        {
            this.DetalleCompras = new HashSet<DetalleCompras>();
        }
    
        public int CompraID { get; set; }
        public Nullable<int> ProveedorID { get; set; }
        public string NumeroFactura { get; set; }
        public Nullable<System.DateTime> FechaCompra { get; set; }
        public decimal SubTotal { get; set; }
        public Nullable<decimal> Impuesto { get; set; }
        public decimal Total { get; set; }
        public string Estado { get; set; }
    
        public virtual Proveedores Proveedores { get; set; }
        public virtual ICollection<DetalleCompras> DetalleCompras { get; set; }
    }
}
