//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppTienda
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        public Productos()
        {
            this.DetalleCompras = new HashSet<DetalleCompras>();
            this.DetalleVentas = new HashSet<DetalleVentas>();
            this.Inventario = new HashSet<Inventario>();
        }
    
        public int ProductoID { get; set; }
        public string CodigoBarra { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> CategoriaID { get; set; }
        public Nullable<int> ProveedorID { get; set; }
        public decimal PrecioCompra { get; set; }
        public decimal PrecioVenta { get; set; }
        public Nullable<int> StockMinimo { get; set; }
        public string UnidadMedida { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        public virtual Categorias Categorias { get; set; }
        public virtual ICollection<DetalleCompras> DetalleCompras { get; set; }
        public virtual ICollection<DetalleVentas> DetalleVentas { get; set; }
        public virtual ICollection<Inventario> Inventario { get; set; }
        public virtual Proveedores Proveedores { get; set; }
    }
}
