//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppTienda
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public Usuarios()
        {
            this.Caja = new HashSet<Caja>();
        }
    
        public int UsuarioID { get; set; }
        public Nullable<int> EmpleadoID { get; set; }
        public string NombreUsuario { get; set; }
        public string Contraseña { get; set; }
        public string Rol { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.DateTime> UltimoLogin { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        public virtual ICollection<Caja> Caja { get; set; }
        public virtual Empleados Empleados { get; set; }
    }
}
