//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppTienda
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ventas
    {
        public Ventas()
        {
            this.DetalleVentas = new HashSet<DetalleVentas>();
        }
    
        public int VentaID { get; set; }
        public string NumeroFactura { get; set; }
        public Nullable<int> ClienteID { get; set; }
        public Nullable<int> EmpleadoID { get; set; }
        public Nullable<System.DateTime> FechaVenta { get; set; }
        public decimal SubTotal { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public Nullable<decimal> Impuesto { get; set; }
        public decimal Total { get; set; }
        public string MetodoPago { get; set; }
        public string Estado { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual ICollection<DetalleVentas> DetalleVentas { get; set; }
        public virtual Empleados Empleados { get; set; }
    }
}
